apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: sairamana33/healthcareproject:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8ssvc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      # Uncomment the following line if you need a specific nodePort
      # nodePort: 30000 # Example nodePort value (should be in the range 30000-32767)
  type: NodePort
